name: Deploy Lambda

on:
  push:
    tags:
      - "deploy-*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # AWS 인증 설정
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # github secret
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Build and deploy
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          CSS_PATH: ${{ secrets.CSS_PATH }}
        # --build arg : Dockerfile ARG 환경변수 전달
        run: |
          docker build \
            --build-arg S3_BUCKET=$S3_BUCKET \
            --build-arg CSS_PATH=$CSS_PATH \
            -t lambda-function:${{ github.ref_name }} .

          aws lambda update-function-code \
            --function-name ${{secrets.LAMBDA_FUNCTION_NAME}} \
            --image-uri $IMAGE_NAME:${{github.ref_name}}
